export default {
    type: "container",
    display: "flex",
    flex_direction: "column",
    justify_content: "start",
    align_items: "start",
    width: "10",
    height: "10",
    background: "#FFFFFF",
    id: "container01",
    children: [
        {
            id: "input01",
            type: "input",
            width: "10",
            height: "50px",
            hint: "请输入日程主题",
            margin: "5 px",
            textSize: "15",
            textColor: "#545454",
            textStyle: "bold",
        },
        {
            id: "input02",
            type: "input",
            width: "10",
            height: "50px",
            hint: "请输入日程内容",
            margin: "5px",
            textSize: "12",
            textColor: "#545454",
        },
        {
            id: "space01",
            type: "spaceView",
            width: "10",
            height: "1px",
            background: "#d8d8d8"
        },
        {
            id: "container02",
            type: "container",
            display: "flex",
            flex_direction: "row",
            justify_content: "space-between",
            align_items: "start",
            width: "10",
            height: "-1",
            children: [
                {
                    id: "container03",
                    type: "container",
                    display: "flex",
                    flex_direction: "column",
                    justify_content: "center",
                    align_items: "center",
                    width: "5",
                    height: "100px",
                    children: [
                        {
                            id: "text01",
                            type: "text",
                            width: "5",
                            height: "-1",
                            text: "开始",
                            textSize: "12",
                            textColor: "#545454",
                        },
                        {
                            id: "text02",
                            type: "text",
                            width: "5",
                            height: "-1",
                            text: "2019/06/28 15:00",
                            textSize: "12",
                            textColor: "#545454",
                        },
                    ]
                },
                {
                    id: "space02",
                    type: "spaceView",
                    width: "1px",
                    height: "10",
                    background: "#d8d8d8"
                },
                {
                    id: "container03",
                    type: "container",
                    display: "flex",
                    flex_direction: "column",
                    justify_content: "center",
                    align_items: "center",
                    width: "5",
                    height: "100px",
                    children: [
                        {
                            id: "text03",
                            type: "text",
                            width: "5",
                            height: "-1",
                            text: "结束",
                            textSize: "12",
                            textColor: "#545454",
                        },
                        {
                            id: "text04",
                            type: "text",
                            width: "5",
                            height: "-1",
                            text: "2019/06/28 16:00",
                            textSize: "12",
                            textColor: "#545454",
                        },
                    ]
                },
            ]
        },
        {
            id: "space03",
            type: "spaceView",
            height: "20px",
            width: "1",
            background: "#b7d0d0"
        },
        {
            id: "container04",
            type: "container",
            display: "flex",
            flex_direction: "row",
            justify_content: "space-between",
            align_items: "start",
            width: "10",
            height: "50px",
            children: [
                {
                    id: "icon01",
                    type: "icon",
                    width: "32px",
                    height: "32px",
                    src: "ico_event_tag.png",
                    textSize: "12",
                    textColor: "#545454",
                },
                {
                    id: "input03",
                    type: "input",
                    width: "1",
                    height: "32px",
                    hint: "请输入标签",
                    textSize: "12",
                    textColor: "#545454",
                },
            ],
        },
    ],
}
